import type { Role } from './roles';
import type { CommunicationPermissions } from '../types/communication';

export const COMMUNICATION_RULES: Record<Role, CommunicationPermissions> = {
  SUPER_ADMIN: {
    canBroadcastGlobal: true,
    canBroadcastSchool: true,
    canBroadcastClass: true,
    canBroadcastDepartment: true,
    canMessageRoles: [
      'SUPER_ADMIN', 'SCHOOL_ADMIN', 'VICE_PRINCIPAL', 'HOD', 'ACADEMIC_COORDINATOR', 
      'EXAM_CONTROLLER', 'TEACHER', 'CLASS_TEACHER', 'LAB_INSTRUCTOR', 'STUDENT', 
      'PARENT', 'ADMISSION_OFFICER', 'OFFICE_ADMIN', 'ACCOUNTANT', 'HR_MANAGER', 
      'TRANSPORT_MANAGER', 'BUS_DRIVER', 'HOSTEL_WARDEN', 'LIBRARIAN', 'IT_ADMIN'
    ],
    requiresApprovalForBroadcast: false,
    canApproveBroadcasts: true,
    visibleScopes: ['GLOBAL', 'SCHOOL', 'DEPARTMENT', 'CLASS', 'SECTION', 'INDIVIDUAL', 'ROLE_BASED', 'TRANSPORT_ROUTE', 'HOSTEL_BLOCK'],
  },
  SCHOOL_ADMIN: {
    canBroadcastGlobal: false,
    canBroadcastSchool: true,
    canBroadcastClass: true,
    canBroadcastDepartment: true,
    canMessageRoles: [
      'SCHOOL_ADMIN', 'VICE_PRINCIPAL', 'HOD', 'ACADEMIC_COORDINATOR', 
      'EXAM_CONTROLLER', 'TEACHER', 'CLASS_TEACHER', 'LAB_INSTRUCTOR', 'STUDENT', 
      'PARENT', 'ADMISSION_OFFICER', 'OFFICE_ADMIN', 'ACCOUNTANT', 'HR_MANAGER', 
      'TRANSPORT_MANAGER', 'BUS_DRIVER', 'HOSTEL_WARDEN', 'LIBRARIAN', 'IT_ADMIN'
    ],
    requiresApprovalForBroadcast: false,
    canApproveBroadcasts: true,
    visibleScopes: ['SCHOOL', 'DEPARTMENT', 'CLASS', 'SECTION', 'INDIVIDUAL', 'ROLE_BASED', 'TRANSPORT_ROUTE', 'HOSTEL_BLOCK'],
  },
  TEACHER: {
    canBroadcastGlobal: false,
    canBroadcastSchool: false,
    canBroadcastClass: true,
    canBroadcastDepartment: false,
    canMessageRoles: ['STUDENT', 'PARENT', 'TEACHER', 'HOD', 'SCHOOL_ADMIN'],
    requiresApprovalForBroadcast: true,
    canApproveBroadcasts: false,
    visibleScopes: ['CLASS', 'SECTION', 'INDIVIDUAL', 'DEPARTMENT'],
  },
  STUDENT: {
    canBroadcastGlobal: false,
    canBroadcastSchool: false,
    canBroadcastClass: false,
    canBroadcastDepartment: false,
    canMessageRoles: ['TEACHER', 'CLASS_TEACHER'],
    requiresApprovalForBroadcast: false,
    canApproveBroadcasts: false,
    visibleScopes: ['CLASS', 'SECTION', 'INDIVIDUAL'],
  },
  PARENT: {
    canBroadcastGlobal: false,
    canBroadcastSchool: false,
    canBroadcastClass: false,
    canBroadcastDepartment: false,
    canMessageRoles: ['TEACHER', 'CLASS_TEACHER', 'SCHOOL_ADMIN', 'ACCOUNTANT'],
    requiresApprovalForBroadcast: false,
    canApproveBroadcasts: false,
    visibleScopes: ['INDIVIDUAL', 'CLASS', 'SECTION'],
  },
  ACCOUNTANT: {
    canBroadcastGlobal: false,
    canBroadcastSchool: false,
    canBroadcastClass: false,
    canBroadcastDepartment: false,
    canMessageRoles: ['PARENT', 'SCHOOL_ADMIN', 'OFFICE_ADMIN'],
    requiresApprovalForBroadcast: true,
    canApproveBroadcasts: false,
    visibleScopes: ['INDIVIDUAL', 'ROLE_BASED'],
  },
  IT_ADMIN: {
    canBroadcastGlobal: true,
    canBroadcastSchool: true,
    canBroadcastClass: true,
    canBroadcastDepartment: true,
    canMessageRoles: [
      'SUPER_ADMIN', 'SCHOOL_ADMIN', 'IT_ADMIN'
    ],
    requiresApprovalForBroadcast: false,
    canApproveBroadcasts: true,
    visibleScopes: ['GLOBAL', 'SCHOOL', 'INDIVIDUAL', 'ROLE_BASED'],
  },
  // Default for others
  VICE_PRINCIPAL: {
    canBroadcastGlobal: false,
    canBroadcastSchool: true,
    canBroadcastClass: true,
    canBroadcastDepartment: true,
    canMessageRoles: ['TEACHER', 'STUDENT', 'PARENT', 'SCHOOL_ADMIN'],
    requiresApprovalForBroadcast: false,
    canApproveBroadcasts: true,
    visibleScopes: ['SCHOOL', 'DEPARTMENT', 'CLASS', 'SECTION', 'INDIVIDUAL'],
  },
  HOD: {
    canBroadcastGlobal: false,
    canBroadcastSchool: false,
    canBroadcastClass: true,
    canBroadcastDepartment: true,
    canMessageRoles: ['TEACHER', 'STUDENT', 'PARENT', 'SCHOOL_ADMIN', 'VICE_PRINCIPAL'],
    requiresApprovalForBroadcast: true,
    canApproveBroadcasts: false,
    visibleScopes: ['DEPARTMENT', 'CLASS', 'SECTION', 'INDIVIDUAL'],
  },
  ACADEMIC_COORDINATOR: {
    canBroadcastGlobal: false,
    canBroadcastSchool: false,
    canBroadcastClass: true,
    canBroadcastDepartment: true,
    canMessageRoles: ['TEACHER', 'SCHOOL_ADMIN', 'VICE_PRINCIPAL'],
    requiresApprovalForBroadcast: true,
    canApproveBroadcasts: false,
    visibleScopes: ['SCHOOL', 'DEPARTMENT', 'CLASS'],
  },
  EXAM_CONTROLLER: {
    canBroadcastGlobal: false,
    canBroadcastSchool: true,
    canBroadcastClass: true,
    canBroadcastDepartment: false,
    canMessageRoles: ['TEACHER', 'STUDENT', 'PARENT', 'SCHOOL_ADMIN'],
    requiresApprovalForBroadcast: false,
    canApproveBroadcasts: true,
    visibleScopes: ['SCHOOL', 'CLASS', 'INDIVIDUAL'],
  },
  CLASS_TEACHER: {
    canBroadcastGlobal: false,
    canBroadcastSchool: false,
    canBroadcastClass: true,
    canBroadcastDepartment: false,
    canMessageRoles: ['STUDENT', 'PARENT', 'TEACHER', 'SCHOOL_ADMIN'],
    requiresApprovalForBroadcast: false,
    canApproveBroadcasts: false,
    visibleScopes: ['CLASS', 'SECTION', 'INDIVIDUAL'],
  },
  LAB_INSTRUCTOR: {
    canBroadcastGlobal: false,
    canBroadcastSchool: false,
    canBroadcastClass: true,
    canBroadcastDepartment: false,
    canMessageRoles: ['TEACHER', 'STUDENT'],
    requiresApprovalForBroadcast: true,
    canApproveBroadcasts: false,
    visibleScopes: ['CLASS', 'SECTION', 'INDIVIDUAL'],
  },
  ADMISSION_OFFICER: {
    canBroadcastGlobal: false,
    canBroadcastSchool: false,
    canBroadcastClass: false,
    canBroadcastDepartment: false,
    canMessageRoles: ['PARENT', 'SCHOOL_ADMIN', 'OFFICE_ADMIN'],
    requiresApprovalForBroadcast: true,
    canApproveBroadcasts: false,
    visibleScopes: ['INDIVIDUAL', 'ROLE_BASED'],
  },
  OFFICE_ADMIN: {
    canBroadcastGlobal: false,
    canBroadcastSchool: true,
    canBroadcastClass: false,
    canBroadcastDepartment: false,
    canMessageRoles: ['TEACHER', 'PARENT', 'SCHOOL_ADMIN'],
    requiresApprovalForBroadcast: true,
    canApproveBroadcasts: false,
    visibleScopes: ['SCHOOL', 'INDIVIDUAL'],
  },
  HR_MANAGER: {
    canBroadcastGlobal: false,
    canBroadcastSchool: true,
    canBroadcastClass: false,
    canBroadcastDepartment: false,
    canMessageRoles: ['TEACHER', 'SCHOOL_ADMIN', 'SUPER_ADMIN'],
    requiresApprovalForBroadcast: false,
    canApproveBroadcasts: true,
    visibleScopes: ['SCHOOL', 'INDIVIDUAL', 'ROLE_BASED'],
  },
  TRANSPORT_MANAGER: {
    canBroadcastGlobal: false,
    canBroadcastSchool: true,
    canBroadcastClass: false,
    canBroadcastDepartment: false,
    canMessageRoles: ['BUS_DRIVER', 'PARENT', 'SCHOOL_ADMIN'],
    requiresApprovalForBroadcast: false,
    canApproveBroadcasts: true,
    visibleScopes: ['SCHOOL', 'TRANSPORT_ROUTE', 'INDIVIDUAL'],
  },
  BUS_DRIVER: {
    canBroadcastGlobal: false,
    canBroadcastSchool: false,
    canBroadcastClass: false,
    canBroadcastDepartment: false,
    canMessageRoles: ['TRANSPORT_MANAGER', 'PARENT'],
    requiresApprovalForBroadcast: false,
    canApproveBroadcasts: false,
    visibleScopes: ['TRANSPORT_ROUTE', 'INDIVIDUAL'],
  },
  HOSTEL_WARDEN: {
    canBroadcastGlobal: false,
    canBroadcastSchool: false,
    canBroadcastClass: false,
    canBroadcastDepartment: false,
    canMessageRoles: ['STUDENT', 'PARENT', 'SCHOOL_ADMIN'],
    requiresApprovalForBroadcast: false,
    canApproveBroadcasts: false,
    visibleScopes: ['HOSTEL_BLOCK', 'INDIVIDUAL'],
  },
  LIBRARIAN: {
    canBroadcastGlobal: false,
    canBroadcastSchool: true,
    canBroadcastClass: false,
    canBroadcastDepartment: false,
    canMessageRoles: ['STUDENT', 'TEACHER', 'SCHOOL_ADMIN'],
    requiresApprovalForBroadcast: true,
    canApproveBroadcasts: false,
    visibleScopes: ['SCHOOL', 'INDIVIDUAL'],
  },
};
